// AUTO-GENERATED by scripts/sync-activepieces.ts -- DO NOT EDIT BY HAND.
// Captures the activepieces commit + tag this directory was vendored from.
// Used as a cache-key input by the engine bundle build so a re-sync
// invalidates the cached bundle even though dep versions are unchanged.

export const UPSTREAM_PIN_TAG = "0.82.1";
export const UPSTREAM_PIN_SHA = "d04e6807c485ecd788a72af0d04abffba78563c7";
